name: Cleanup Bucket
description: Composite action to delete mock bucket
runs:
  using: composite
  steps:
      - name: Cleanup Bucket
        shell: bash
        run: |
          # Check if the S3 bucket exists
          BUCKET_EXISTS=$(aws s3api head-bucket --bucket "$BUCKET_NAME" --region ${{ secrets.AWS_REGION }} 2>&1 || true)

          if [[ "$BUCKET_EXISTS" == *"NotFound"* ]]; then
            echo "Mock bucket already cleaned up or never created."
          else
            # Delete all object versions if any exist
            OBJECT_VERSIONS=$(aws s3api list-object-versions --bucket "$BUCKET_NAME" --query "Versions[].[Key,VersionId]" --output text || true)

            if [[ -n "$OBJECT_VERSIONS" && "$OBJECT_VERSIONS" != "None" ]]; then
              echo "$OBJECT_VERSIONS" | while read -r key version_id; do
                if [[ -n "$key" && -n "$version_id" ]]; then
                  echo "Deleting version $version_id of object $key..."
                  aws s3api delete-object --bucket "$BUCKET_NAME" --key "$key" --version-id "$version_id"
                fi
              done
              echo "All object versions deleted."
            else
              echo "No object versions found."
            fi

            # Remove the bucket after deleting objects
            aws s3 rb s3://"$BUCKET_NAME" --force --region ${{ secrets.AWS_REGION }}
            echo "Bucket removed."
          fi