name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  TF_VERSION: 1.10.5

jobs:
  destroy-infrastructure:
    permissions:
      id-token: write 
      contents: read 
    name: Destroy Terraform Infrastructure (excluding S3 backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (Assume Management Account Role)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.MANAGEMENT_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Assume Env Based Role
        uses: ./.github/actions/assume_env_based_role

      - name: Initialize Terraform (Main)
        working-directory: terraform
        run: terraform init -backend-config="bucket=yorkshire-demo-tf-state-bucket-storage" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="encrypt=true"

      - name: Plan Terraform Destroy
        working-directory: terraform
        run: terraform plan -destroy -var-file=${{ github.event.inputs.environment }}.tfvars

      - name: Apply Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve -var-file=${{ github.event.inputs.environment }}.tfvars
