name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  TF_VERSION: 1.5.7

jobs:
  destroy-infrastructure:
    name: Destroy Terraform Infrastructure (excluding S3 backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set AWS Credentials for the Environment
        id: set-aws-credentials
        run: |
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            echo "AWS_ROLE_ARN=${{ secrets.TFDEV_ROLE_ARN }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "AWS_ROLE_ARN=${{ secrets.TFSTAGING_ROLE_ARN }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "AWS_ROLE_ARN=${{ secrets.TFPROD_ROLE_ARN }}" >> $GITHUB_ENV
          fi

      - name: Assume Role and Set Credentials
        uses: aws-actions/aws-assume-role-action@v1
        with:
          role-arn: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession
          aws-region: ${{ secrets.AWS_REGION }}
        id: assume-role

      - name: Initialize Terraform (Main)
        working-directory: terraform
        run: terraform init -backend-config="bucket=york-demo-tf-state-bucket-storage" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="encrypt=true"

      - name: Plan Terraform Destroy
        working-directory: terraform
        run: terraform plan -destroy -var-file=${{ github.event.inputs.environment }}.tfvars

      - name: Apply Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve -var-file=${{ github.event.inputs.environment }}.tfvars
