name: CI Terraform Plan

on:
  push:
    branches:
      - main  # Trigger on every push to the main branch

env:
  TF_VERSION: 1.5.7

jobs:
  terraform:
    name: Terraform VPC and EC2 Deployment Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform (Local Backend)
        working-directory: terraform
        run: terraform init -backend=false

      - name: Validate Terraform Code
        working-directory: terraform
        run: terraform validate

      - name: Plan Terraform Changes Dev (Only Plan, Do Not Apply)
        working-directory: terraform
        run: terraform plan -var-file=dev.tfvars

      - name: Plan Terraform Changes Staging (Only Plan, Do Not Apply)
        working-directory: terraform
        run: terraform plan -var-file=staging.tfvars

      - name: Plan Terraform Changes Prod (Only Plan, Do Not Apply)
        working-directory: terraform
        run: terraform plan -var-file=prod.tfvars
