name: CI Terraform Plan

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.10.5
  BUCKET_NAME: yorkshire-demo-tf-state-bucket-storage-mock
  GITHUB_ENVIRONMENT: dev

jobs:
  terraform:
    permissions:
      id-token: write 
      contents: read 
    name: Terraform VPC and EC2 Deployment Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (Assume Management Account Role)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.MANAGEMENT_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Assume Env Based Role
        uses: ./.github/actions/assume_env_based_role

      - name: Create Temp S3 Backend (Temporary)
        run: |
          aws s3 mb s3://"$BUCKET_NAME" --region ${{ secrets.AWS_REGION }}
          # Wait for a few seconds to ensure the bucket is available for the next steps
          sleep 90

      - name: Initialize Terraform (Main)
        working-directory: terraform
        run: terraform init -backend-config="bucket=${{ env.BUCKET_NAME }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="encrypt=true"
  
      - name: Validate Terraform Code
        working-directory: terraform
        run: terraform validate

      - name: Terraform Test VPC And EC2
        working-directory: terraform
        run: terraform test -var-file=dev.tfvars

      - name: Plan Terraform Changes Dev
        working-directory: terraform
        run: terraform plan -var-file=dev.tfvars

      - name: Assume Env Based Role
        uses: ./.github/actions/cleanup_bucket

