name: Code Integration Tests / TF plan

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.5.7
  BUCKET_NAME: york-demo-tf-state-bucket-storage-mock

jobs:
  terraform:
    name: Terraform VPC and EC2 Deployment Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Temp S3 Backend (Temporary)
        run: |
          aws s3 mb s3://"$BUCKET_NAME" --region ${{ secrets.AWS_REGION }}
          sleep 90  # Ensure bucket availability

      - name: Initialize Terraform (Main)
        working-directory: terraform
        run: terraform init -backend-config="bucket=${{ env.BUCKET_NAME }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="encrypt=true"
  
      - name: Validate Terraform Code
        working-directory: terraform
        run: terraform validate

      # ---- DEV PLAN & COMPLIANCE ----
      - name: Plan Terraform Changes Dev
        working-directory: terraform
        run: |
          terraform plan -var-file=dev.tfvars -out=tfplan-dev.json
          # terraform show -json tfplan-dev > tfplan-dev.json

      - name: Run terraform-compliance for Dev
        run: |
          docker run --rm \
            -v "$(pwd):/target" \
            eerkunt/terraform-compliance \
            -p /target/terraform/tfplan-dev.json --features /target/compliance/

      # ---- STAGING PLAN & COMPLIANCE ----
      - name: Plan Terraform Changes Staging
        working-directory: terraform
        run: |
          terraform plan -var-file=staging.tfvars -out=tfplan-staging.json
          # terraform show -json tfplan-staging > tfplan-staging.json

      - name: Run terraform-compliance for Staging
        run: |
          docker run --rm \
            -v "$(pwd):/target" \
            eerkunt/terraform-compliance \
            -p /target/terraform/tfplan-staging.json --features /target/compliance/

      # ---- PROD PLAN & COMPLIANCE ----
      - name: Plan Terraform Changes Prod
        working-directory: terraform
        run: |
          terraform plan -var-file=prod.tfvars -out=tfplan-prod.json
          # terraform show -json tfplan-prod > tfplan-prod.json

      - name: Run terraform-compliance for Prod
        run: |
          docker run --rm \
            -v "$(pwd):/target" \
            eerkunt/terraform-compliance \
            -p /target/terraform/tfplan-prod.json --features /target/compliance/

      - name: Cleanup Mock Bucket
        run: |
          BUCKET_EXISTS=$(aws s3api head-bucket --bucket "$BUCKET_NAME" --region ${{ secrets.AWS_REGION }} 2>&1 || true)

          if [[ "$BUCKET_EXISTS" == *"NotFound"* ]]; then
            echo "Mock bucket already cleaned up or never created."
          else
            OBJECT_VERSIONS=$(aws s3api list-object-versions --bucket "$BUCKET_NAME" --query "Versions[].[Key,VersionId]" --output text || true)

            if [[ -n "$OBJECT_VERSIONS" && "$OBJECT_VERSIONS" != "None" ]]; then
              echo "$OBJECT_VERSIONS" | while read -r key version_id; do
                if [[ -n "$key" && -n "$version_id" ]]; then
                  echo "Deleting version $version_id of object $key..."
                  aws s3api delete-object --bucket "$BUCKET_NAME" --key "$key" --version-id "$version_id"
                fi
              done
              echo "All object versions deleted."
            else
              echo "No object versions found."
            fi

            aws s3 rb s3://"$BUCKET_NAME" --force --region ${{ secrets.AWS_REGION }}
            echo "Bucket removed."
          fi
